---
# Make Hadoop properties dictionary
- name: "HADOOP CONFIG| Setup Hadoop properties"
  set_fact:
    hadoop_properties: "{{ default_hadoop_properties | combine( hadoop_properties|default({}), recursive=true ) }}"

# Common configuration procedure
- name: "HADOOP CONFIG| Create Hadoop configuration for '{{ _hadoop_version }}'"
  import_role: 
    name: soliverr.bigdata.config
  vars:
    bigdata_owner: "{{ (hadoop_user_create) | ternary(hadoop_user, 'root') }}"
    bigdata_group: "{{ (hadoop_user_create) | ternary(hadoop_group, 'root') }}"
    bigdata_install_dir: "{{ hadoop_install_dir }}"
    bigdata_configuration_pristine_dir: "{{ hadoop_install_dir }}/etc/hadoop"
    bigdata_configuration_pristine_copy: true
    bigdata_configuration_base_dir: "{{ hadoop_etc_base_dir }}"
    bigdata_etc_dir: "{{ hadoop_etc_dir }}"
    bigdata_log_dir: "{{ hadoop_log_dir }}"
    bigdata_profile_name: "{{ hadoop_profile_name }}"
    bigdata_profile_template: 'hadoop-profile.sh.j2'
    bigdata_service_set_default: "{{ _hadoop_service_set_default }}"
    bigdata_env_template: 'hadoop-env.sh.j2'
    bigdata_env_name: "{{ hadoop_env_name }}"
    bigdata_task_suffix: "HADOOP"
