---
# tasks file for ansible-role-hadoop

- name: "HADOOP| Create users and groups"
  import_tasks: create_users.yml
  tags:
    - hadoop
    - hadoop_install
    - hadoop_users

- name: "HADOOP| Install base distribution"
  import_tasks: install.yml
  tags:
    - hadoop
    - hadoop_install
      
- name: "HADOOP| Configure base distribution"
  import_tasks: config.yml
  tags:
    - hadoop
    - hadoop_config
